# This file tells prometheus where to scrape for metrics

global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']
    metrics_path: '/metrics'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # To access metrics port is localhost:9110

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
